# Generated by Django 4.1.7 on 2023-03-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("key", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Question 1", max_length=100)),
                ("text", models.TextField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="questionnaire.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Iteration",
            fields=[
                ("user", models.CharField(max_length=100)),
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iterations",
                        to="questionnaire.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                ("name", models.CharField(default="Option 1", max_length=100)),
                ("key", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answeroptions",
                        to="questionnaire.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additional_information", models.TextField(null=True)),
                (
                    "answer_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.answeroption",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_answers",
                        to="questionnaire.iteration",
                    ),
                ),
            ],
        ),
    ]
